alex - Admin Personal Schedule Placeholder Page and Navbar
ucsb-cs156-w22/team04-w22-5pm-courses pull request #33
Opened 2022-03-02 21:41 UTC by AlexLaiUCSB

# Navbar
![image](https://user-images.githubusercontent.com/49248229/156454195-34ab62a5-5d83-44b4-a8aa-7538a049e6b6.png)
# Placeholder Page w/ Route
![image](https://user-images.githubusercontent.com/49248229/156454255-d98a1fa9-945b-4511-b53d-752da6b07625.png)

# Placeholder Page in Storybook
![image](https://user-images.githubusercontent.com/49248229/156454158-35cba890-d9c3-4f39-afcc-3a7b7fda90c0.png)

2022-03-03 22:28 UTC, andrewpengucsb approved these changes
LGTM!

2022-03-04 21:13 UTC, btk5h requested changes
Overall good first PR, just some unused code that should be cleaned up.

2022-03-04 21:52 UTC, AlexLaiUCSB commented on frontend/src/tests/components/Nav/AppNavbar.test.js
> +import { Dropdown } from "bootstrap";
Yes, removed that import in new commit

2022-03-04 21:53 UTC, btk5h approved these changes

2022-03-04 21:56 UTC, andrewpengucsb submitted a review, later dismissed
Approval for after the changes, LGTM!

2022-03-05 03:39 UTC, andrewpengucsb approved these changes
Good stuff, LGTM

2022-03-08 22:33 UTC, andrewpengucsb approved these changes
Placeholder looks good! LGTM

2022-03-08 22:51 UTC, ScottUCSB approved these changes
Looks like a solid placeholder page with a new entry on the Navbar

2022-03-09 21:17 UTC, andrewhlu approved these changes
LGTM! This is a solid 10 point issue!

2022-03-09 21:17 UTC, merged