W22 5pm 2 sg add subj table
ucsb-cs156-w22/team04-w22-5pm-courses pull request #48
Opened 2022-03-08 19:45 UTC by ScottUCSB

![image](https://user-images.githubusercontent.com/91567274/157313093-0b74b94d-2ed6-4d46-afdd-c35b41ac0c93.png)

Renamed the branch to follow the guidelines if looking for more history on this, check out closed branch "sg-W22 5pm 2 sg add subj table"

2022-03-09 01:15 UTC, AlexLaiUCSB requested changes

2022-03-09 01:15 UTC, AlexLaiUCSB commented on frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
> +        navigate(`/ucsbsubjects/edit/${cell.row.values.id}`)
This is the API mismatch I am talking about. Controllers uses `/UCSBSubjects` and frontend table uses `/ucsbsubjects`
![image](https://user-images.githubusercontent.com/49248229/157352419-e7f38712-f148-4d1b-8fc2-526504a77acd.png)

2022-03-09 01:15 UTC, AlexLaiUCSB commented on frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
> +        ["/api/ucsbsubjects/all"]
Similarly api mismatch here

2022-03-09 01:15 UTC, AlexLaiUCSB commented on frontend/src/main/utils/UCSBSubjectUtils.js
> +        url: "/api/ucsbsubjects",
API mismatch here too

2022-03-09 01:15 UTC, AlexLaiUCSB commented on frontend/src/tests/utils/UCSBSubjectUtils.test.js
> +                url: "/api/ucsbsubjects",
Also might need to change api here

2022-03-09 06:32 UTC, AlexLaiUCSB requested changes

2022-03-09 06:32 UTC, AlexLaiUCSB commented on frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
> +        navigate(`/UCSBsubjects/edit/${cell.row.values.id}`)
Capitalize the s in `UCSBsubjects` to match the controller. Should be `UCSBSubjects`
![image](https://user-images.githubusercontent.com/49248229/157384695-0c69720e-bef0-49fa-9b17-ae4e7193b19c.png)

2022-03-09 06:32 UTC, AlexLaiUCSB commented on frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
> +        ["/api/UCSBsubjects/all"]
`UCSBSubjects` here

2022-03-09 06:32 UTC, AlexLaiUCSB commented on frontend/src/main/utils/UCSBSubjectUtils.js
> +        url: "/api/UCSBsubjects",
`UCSBSubjects` here too

2022-03-09 06:32 UTC, AlexLaiUCSB commented on frontend/src/tests/utils/UCSBSubjectUtils.test.js
> +                url: "/api/UCSBsubjects",
`UCSBSubjects` here too

2022-03-09 06:32 UTC, AlexLaiUCSB commented on frontend/src/tests/components/UCSBSubjects/UCSBSubjectsTable.test.js
> +    await waitFor(() => expect(mockedNavigate).toHaveBeenCalledWith('/UCSBsubjects/edit/1'));
`UCSBSubjects`

2022-03-09 06:32 UTC, AlexLaiUCSB commented on frontend/src/main/utils/UCSBSubjectUtils.js
> +import { useNavigate } from 'react-router-dom'
this import is not used, probably delete it

2022-03-09 06:32 UTC, AlexLaiUCSB commented on frontend/src/tests/utils/UCSBSubjectUtils.test.js
> +import { onDeleteSuccess, cellToAxiosParamsDelete, editCallback } from "main/utils/UCSBSubjectUtils";
remove editCallback as UCSBSubjectUtils doesn't have that function anymore

2022-03-09 18:48 UTC, AlexLaiUCSB approved these changes
LGTM

2022-03-10 00:35 UTC, pconrad requested changes
Please consider using real data in your fixtures instead of fake data.

2022-03-10 00:35 UTC, pconrad commented on frontend/src/fixtures/ucsbSubjectsFixtures.js
> +};
Please considering use real data from the UCSB Subjects API in your fixtures instead of fake data like this.

2022-03-10 02:54 UTC, ScottUCSB commented
![image](https://user-images.githubusercontent.com/91567274/157579215-10490f35-98b8-4632-b58f-62045615d46f.png)

2022-03-10 18:05 UTC, pconrad approved these changes
LGTM

2022-03-10 19:13 UTC, merged